version: 2
machine:
  services:
    - docker
jobs:
  build:
    working_directory: /go/src/github.com/CircleCI-Public/consul-envoy-xds
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - restore_cache:
          keys:
          - vendor-pkg-{{ checksum "Gopkg.lock" }}
          - vendor-pkg-
      - run:
          name: Install Dependencies
          command: |
            make setup
      - save_cache:
          paths:
            - ./vendor
            - "/go/pkg"
          key: vendor-pkg-{{ checksum "Gopkg.lock" }}
      - run:
          name: Run tests
          command: |
            make test
      - run:
          name: Docker Build
          command: |
            docker build -t gojektech/consul-envoy-xds:${CIRCLE_SHA1} .
deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push gojektech/consul-envoy-xds:${CIRCLE_SHA1}
